# Generated by Django 5.0.1 on 2024-01-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='group',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject_name',
        ),
    ]
