# Generated by Django 5.0.1 on 2024-01-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=50)),
                ('group_name', models.CharField(max_length=100)),
                ('trello_link', models.URLField()),
                ('figma_link', models.URLField()),
                ('other', models.CharField(max_length=500)),
            ],
        ),
    ]
