# Generated by Django 5.0.1 on 2024-01-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='figma_link',
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='other',
        ),
        migrations.RemoveField(
            model_name='group',
            name='trello_link',
        ),
        migrations.AddField(
            model_name='group',
            name='subject_name',
            field=models.CharField(default='project', max_length=50),
        ),
    ]
