# Generated by Django 5.0.1 on 2024-01-18 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0004_group_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyScrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yesterday', models.CharField(max_length=1000)),
                ('today', models.CharField(max_length=1000)),
                ('problem', models.CharField(max_length=1000)),
                ('note', models.CharField(choices=[('work', 'วันนี้ทำงาน'), ('sick', 'ป่วย'), ('busy.', 'ติดธุระ'), ('pass', 'ตกลงกันว่าวันนี้ไม่ทำงาน'), ('other', 'อื่นๆ (โปรดระบุ)')], max_length=5)),
                ('other_description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
